<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Brands</name>
   <tag></tag>
   <elementGuidId>b2bf8e81-5f30-4f4c-8ad6-1d2a593f84d8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='content']/div/ul/li[2]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>f13bd4d3-4349-4c71-a215-5dafbf3c3a4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-link</value>
      <webElementGuid>69c8b376-19cb-49dc-8cd1-19366c7d1c75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://ecommerce-playground.lambdatest.io/index.php?route=extension/maza/account/notification/manufacturer</value>
      <webElementGuid>ce74e161-1461-48f9-b7bf-877e3b8d8c6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Brands</value>
      <webElementGuid>9acdcf47-8a60-4ed0-817a-fa3f7104c999</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;content&quot;)/div[@class=&quot;buttons clearfix my-4&quot;]/ul[@class=&quot;nav nav-pills bg-light float-left&quot;]/li[@class=&quot;nav-item&quot;]/a[@class=&quot;nav-link&quot;]</value>
      <webElementGuid>5d24cc33-2eef-4180-b43c-f048f0238599</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/div/ul/li[2]/a</value>
      <webElementGuid>a552158b-dd0e-4d4e-aa91-22281f0ce689</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Brands')]</value>
      <webElementGuid>a6aab830-c4b3-46c3-a722-797158ec21dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Products'])[1]/following::a[1]</value>
      <webElementGuid>6811ff0a-4411-4ba8-93a2-90a2ea06ed42</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Subscribed products'])[3]/following::a[2]</value>
      <webElementGuid>401bb74b-5d97-42b0-9a56-9921dd8acb46</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Continue'])[1]/preceding::a[1]</value>
      <webElementGuid>5de5663b-1bd7-4088-8ca2-ee45ec3e7c37</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Brands']/parent::*</value>
      <webElementGuid>0ec62154-dadd-4a94-bf76-362117da0d9c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://ecommerce-playground.lambdatest.io/index.php?route=extension/maza/account/notification/manufacturer')]</value>
      <webElementGuid>a4c4e882-4131-428f-99de-6949b7aa5517</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/div/div/ul/li[2]/a</value>
      <webElementGuid>14335a6a-586c-49a9-a892-4b42dcb3fb68</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://ecommerce-playground.lambdatest.io/index.php?route=extension/maza/account/notification/manufacturer' and (text() = 'Brands' or . = 'Brands')]</value>
      <webElementGuid>620214ad-1d49-4e17-abda-901be568793d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
