<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Desktops_figure-img img-fluid lazy-load</name>
   <tag></tag>
   <elementGuidId>5eaeff6c-706d-4861-b7a8-50dfc9d7026a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='swiper-wrapper-588cba88cb5b5979']/div[2]/a/figure/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.swiper-slide.swiper-slide-next > a > figure.figure.img-top > div.figure-img-wrapper > img.figure-img.img-fluid.lazy-load</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>02a5b621-7504-42d9-b776-ef59b0b84620</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>figure-img img-fluid lazy-load</value>
      <webElementGuid>db5ab898-05f6-4497-a873-cd802e0faefa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://ecommerce-playground.lambdatest.io/image/cache/catalog/maza/demo/mz_poco/megastore-2/category/5-150x150.webp</value>
      <webElementGuid>2bc2a4a5-db06-4399-8b2b-9796aba1dcac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>150</value>
      <webElementGuid>498fcf9c-5225-431f-acfb-7bd60f38167b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>150</value>
      <webElementGuid>1e96bd58-090b-47e4-bdb0-fd616253b01c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Laptops</value>
      <webElementGuid>47bb6408-7c9a-4860-bc02-c58cb325ad4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;swiper-wrapper-588cba88cb5b5979&quot;)/div[@class=&quot;swiper-slide swiper-slide-next&quot;]/a[1]/figure[@class=&quot;figure img-top&quot;]/div[@class=&quot;figure-img-wrapper&quot;]/img[@class=&quot;figure-img img-fluid lazy-load&quot;]</value>
      <webElementGuid>b88e6c25-fce7-4577-829e-44b8b61beedd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='swiper-wrapper-588cba88cb5b5979']/div[2]/a/figure/div/img</value>
      <webElementGuid>1add8eae-56d9-4af3-ba71-ce5682fb1f65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Laptops']</value>
      <webElementGuid>72c57e51-c4f3-43db-9f6a-25aa66ccef62</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/a/figure/div/img</value>
      <webElementGuid>1831777b-3a90-40af-9a02-b4c0e10cfa5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://ecommerce-playground.lambdatest.io/image/cache/catalog/maza/demo/mz_poco/megastore-2/category/5-150x150.webp' and @alt = 'Laptops']</value>
      <webElementGuid>fe46cde4-b1de-4d5a-87e1-7190a76bf0b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='swiper-wrapper-de4107da9882ec13d']/div[2]/a/figure/div/img</value>
      <webElementGuid>9cd1bddd-9223-4548-9603-8c50ba8db1c9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
