<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Next_lazy-load</name>
   <tag></tag>
   <elementGuidId>58c9e088-ee43-4483-b3f6-a654a8d41170</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.hover-effect.hover-effect-6 > img.lazy-load</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='entry_213245']/a/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>ce0bae4f-85da-41f5-82b4-86cf3ed7f4e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lazy-load</value>
      <webElementGuid>2efaf8e1-7e7e-49e8-b3d0-4169e91e5690</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://ecommerce-playground.lambdatest.io/image/cache/catalog/maza/demo/mz_poco/megastore-2/banner/middle-banner-2-580x234.webp</value>
      <webElementGuid>59900d32-2703-41f3-a138-08a517759118</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>580</value>
      <webElementGuid>7182e9c5-4dec-46f9-a19d-2eac574646d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>234</value>
      <webElementGuid>696cf9b1-3ccd-4bf5-b42b-bf862f7ed3f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>MPOW H12 RC Headphone</value>
      <webElementGuid>abb6a7ad-06a1-4c60-b472-028658135ee2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sizes</name>
      <type>Main</type>
      <value>(min-width: 1360px) 580px,(min-width: 1024px) 542px,(min-width: 768px) 444px,(min-width: 576px) 384px,287px</value>
      <webElementGuid>8826c723-279a-4356-829d-14366f3379ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>srcset</name>
      <type>Main</type>
      <value>https://ecommerce-playground.lambdatest.io/image/cache/catalog/maza/demo/mz_poco/megastore-2/banner/middle-banner-2-542x218.webp 542w,https://ecommerce-playground.lambdatest.io/image/cache/catalog/maza/demo/mz_poco/megastore-2/banner/middle-banner-2-444x179.webp 444w,https://ecommerce-playground.lambdatest.io/image/cache/catalog/maza/demo/mz_poco/megastore-2/banner/middle-banner-2-384x154.webp 384w,https://ecommerce-playground.lambdatest.io/image/cache/catalog/maza/demo/mz_poco/megastore-2/banner/middle-banner-2-287x115.webp 287w,https://ecommerce-playground.lambdatest.io/image/cache/catalog/maza/demo/mz_poco/megastore-2/banner/middle-banner-2-580x234.webp 580w</value>
      <webElementGuid>489e8db6-1607-4673-ae7a-1646eb49dd80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;entry_213245&quot;)/a[@class=&quot;d-block&quot;]/div[@class=&quot;hover-effect hover-effect-6&quot;]/img[@class=&quot;lazy-load&quot;]</value>
      <webElementGuid>ac7d7e9b-b1af-4d31-a419-e8c9a7e03593</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='entry_213245']/a/div/img</value>
      <webElementGuid>a5ba25a1-f271-4500-9593-610414bf6502</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='MPOW H12 RC Headphone']</value>
      <webElementGuid>976a9991-8557-468d-97e1-4d9014f33b02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/a/div/img</value>
      <webElementGuid>11f6ca26-2194-4c12-9d5a-bb13085c689a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://ecommerce-playground.lambdatest.io/image/cache/catalog/maza/demo/mz_poco/megastore-2/banner/middle-banner-2-580x234.webp' and @alt = 'MPOW H12 RC Headphone']</value>
      <webElementGuid>187978b3-cb48-432d-8214-3993ce7834af</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
