<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Top Trending Categories_figure-img img-_4537bf</name>
   <tag></tag>
   <elementGuidId>1ad17de1-52b4-455e-af02-df3669dbe6d1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.figure-img.img-fluid.lazy-load</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='swiper-wrapper-b5386b6548ab419c']/div/a/figure/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>351cde77-d9fb-45b0-b8ac-96794d8c4591</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>figure-img img-fluid lazy-load</value>
      <webElementGuid>d1b43a0d-ff72-410e-84e0-2c2c73ac60b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://ecommerce-playground.lambdatest.io/image/cache/catalog/maza/demo/mz_poco/megastore-2/category/4-150x150.webp</value>
      <webElementGuid>05f678c6-f633-49b3-9987-b8c5c6a09efd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>150</value>
      <webElementGuid>840a7a89-5fd2-4e06-bb2a-aeb773dfbcd4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>150</value>
      <webElementGuid>3e5f9d86-dd15-4a81-a1d1-7d4a6140c24b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Desktops</value>
      <webElementGuid>c330dae0-ada0-4570-8160-cd73e430bbb5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;swiper-wrapper-b5386b6548ab419c&quot;)/div[@class=&quot;swiper-slide swiper-slide-active&quot;]/a[1]/figure[@class=&quot;figure img-top&quot;]/div[@class=&quot;figure-img-wrapper&quot;]/img[@class=&quot;figure-img img-fluid lazy-load&quot;]</value>
      <webElementGuid>07fe6e94-a08f-41e7-be6c-a075c50a4c2d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='swiper-wrapper-b5386b6548ab419c']/div/a/figure/div/img</value>
      <webElementGuid>e015174b-c80d-4bb6-b5bd-302306a3cda6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Desktops']</value>
      <webElementGuid>f5e1b627-17f9-4d57-97f5-b0f8559c2d40</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//figure/div/img</value>
      <webElementGuid>a6eaddbd-4395-4b2c-8d03-1686420edf9f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://ecommerce-playground.lambdatest.io/image/cache/catalog/maza/demo/mz_poco/megastore-2/category/4-150x150.webp' and @alt = 'Desktops']</value>
      <webElementGuid>1a8aee14-370c-4523-81b0-530bc636ab4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='swiper-wrapper-c6d5e9867982c96e']/div/a/figure/div/img</value>
      <webElementGuid>d5c3380c-e6f4-4b19-ae25-2bd56bd91c2a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='swiper-wrapper-a48cebc4ea2c7c46']/div/a/figure/div/img</value>
      <webElementGuid>0d164a5b-1d18-411c-b89e-a18a7611b9ad</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
