<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_170.00_lazy-load</name>
   <tag></tag>
   <elementGuidId>2ba9690f-a290-4378-9b8f-af9436ada314</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mz-product-listing-image-37213259-0-1 > div.carousel-inner > div.carousel-item.active > img.lazy-load</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='mz-product-listing-image-37213259-0-1']/div/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>245abf6d-400f-4da0-970b-7dfac198cfe0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lazy-load</value>
      <webElementGuid>d40545d3-c9ae-47ab-824c-6b9f2118aae2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://ecommerce-playground.lambdatest.io/image/cache/catalog/maza/demo/mz_poco/megastore-2/product/10-270x338.webp</value>
      <webElementGuid>6a48a4e3-5fd7-422b-988c-ea56cc59d0e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>270</value>
      <webElementGuid>17595735-30f6-4bf9-b540-b20beff7922f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>338</value>
      <webElementGuid>240fd9ef-c5ce-40d3-ad73-92776a2bd49a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>iMac</value>
      <webElementGuid>d41a3cc9-3918-45eb-bae2-f03f136c40a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>iMac</value>
      <webElementGuid>127c6644-a677-4b05-900e-8e448ca1b936</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mz-product-listing-image-37213259-0-1&quot;)/div[@class=&quot;carousel-inner&quot;]/div[@class=&quot;carousel-item active&quot;]/img[@class=&quot;lazy-load&quot;]</value>
      <webElementGuid>99d6e9a9-6728-4cdf-b131-56d0596536d4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='mz-product-listing-image-37213259-0-1']/div/div/img</value>
      <webElementGuid>5eae4b5d-41f8-421d-a71b-c533f2ab6cd3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[@alt='iMac'])[7]</value>
      <webElementGuid>e7274a90-068f-419e-84ff-dfc9f7fad2e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/a/div/div/img</value>
      <webElementGuid>b085289f-7756-4f18-9edd-f260edae7d1c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://ecommerce-playground.lambdatest.io/image/cache/catalog/maza/demo/mz_poco/megastore-2/product/10-270x338.webp' and @alt = 'iMac' and @title = 'iMac']</value>
      <webElementGuid>e6cb7015-7a1f-4d02-87f2-be9f7c558ffd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
