<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_5</name>
   <tag></tag>
   <elementGuidId>d129f995-7bc8-4213-8a91-e6d710bebe8c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>label</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='form-review']/div/span/label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>9faf1382-a24b-4dd2-a9bd-467ec6dd4189</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>rating-5-216860</value>
      <webElementGuid>ba1b4090-eca4-4532-bdcb-b41883ad0e43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>3b76ee05-75aa-431a-b543-78e3c78ce4ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;form-review&quot;)/div[@class=&quot;form-group select-rating d-flex flex-wrap&quot;]/span[@class=&quot;start-form-check&quot;]/label[1]</value>
      <webElementGuid>2de9d4d8-0e35-47a8-b00c-116f27d056ac</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form-review']/div/span/label</value>
      <webElementGuid>054b96ad-7cc3-424a-894a-fa4937022e27</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Easy Return'])[1]/following::label[1]</value>
      <webElementGuid>13e4e10e-b913-4aba-9ec9-4ca8b52479df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Online payment'])[1]/following::label[1]</value>
      <webElementGuid>1469bda8-fead-4a15-bf50-f1aadeab0b65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Write a review'])[1]/preceding::label[6]</value>
      <webElementGuid>38c6b61f-344f-4114-a776-bb8abf91c51f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Write Review'])[1]/preceding::label[6]</value>
      <webElementGuid>3b333a95-c660-4b79-af04-9a26161c03c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label</value>
      <webElementGuid>60b47de2-61a9-47da-b012-8d47828cfb21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = '5' or . = '5')]</value>
      <webElementGuid>fa72cdef-3447-4820-897f-5c6a01cda802</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
