<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Write a review_text</name>
   <tag></tag>
   <elementGuidId>b9669a42-b038-4c68-bd07-83b0c061e5ee</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-review</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='input-review']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>be3d1b1d-0009-4d5f-9851-5809a63ac58e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>2c6f21fd-a835-4da4-9f27-e0ce2905c5a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>f7cb339d-ef99-47a7-9f35-5559b39587a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-review</value>
      <webElementGuid>815da9d4-084b-4a7e-9007-d93946d2f698</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Your Review</value>
      <webElementGuid>36a927aa-463e-4f9e-8d3b-7f6b1f5e06d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Your Review</value>
      <webElementGuid>562d53a8-138e-4785-b15c-77ddf411aecf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control form-control-lg</value>
      <webElementGuid>0da7b73b-f784-4d4d-ae37-b6d3a9a804c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-review&quot;)</value>
      <webElementGuid>d86a4186-f3e5-4511-b374-f9f806d2e3f6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='input-review']</value>
      <webElementGuid>df2ea9fe-4701-4432-b597-fe5b2e2aad51</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form-review']/div[3]/textarea</value>
      <webElementGuid>61c59591-f79c-485d-98b6-c5e138bcc466</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/textarea</value>
      <webElementGuid>6c1f6487-2a65-4ed0-8757-f9a0ec6e7ba0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'text' and @id = 'input-review' and @placeholder = 'Your Review']</value>
      <webElementGuid>c113e00c-f3c0-470a-a858-f243265ad48a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
