<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_146.00_fas fa-cart-plus</name>
   <tag></tag>
   <elementGuidId>eadc14a7-4e49-412a-af7a-0bd206f9bbb3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='content']/div/table/tbody/tr/td[6]/button/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>i.fas.fa-cart-plus</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>1b8c3c9c-441d-497e-b6dd-c4b5a4522edf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fas fa-cart-plus</value>
      <webElementGuid>448cfafc-f704-4636-9f48-9917981f15b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;content&quot;)/div[@class=&quot;table-responsive&quot;]/table[@class=&quot;table table-hover border&quot;]/tbody[1]/tr[1]/td[@class=&quot;text-right text-nowrap&quot;]/button[@class=&quot;btn btn-light btn-sm&quot;]/i[@class=&quot;fas fa-cart-plus&quot;]</value>
      <webElementGuid>10d98387-63a6-4087-84ee-106413faf822</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/div/table/tbody/tr/td[6]/button/i</value>
      <webElementGuid>48c7d695-fae9-4b89-bfdb-5dd8103da26b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[6]/button/i</value>
      <webElementGuid>81c2bb78-0341-4fda-bdfb-e9d2b433158e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='notification-box-top']/div/div[2]/div[2]/div[2]/a/i</value>
      <webElementGuid>40d615b2-72c5-4ac6-874f-46048bcfbc3f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/a/i</value>
      <webElementGuid>62b90f30-3768-4795-aab6-d1d855492a1d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/div/table/tbody/tr/td[6]/a/i</value>
      <webElementGuid>24c8d397-af8c-4b73-a333-b6649bb88d98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[6]/a/i</value>
      <webElementGuid>9345c8d4-f384-4357-a287-5bc980db5288</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/div/table/tbody/tr[2]/td[6]/button/i</value>
      <webElementGuid>f4db21cd-570b-4faa-94ec-f6539a872ee4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[6]/button/i</value>
      <webElementGuid>7b77dcb2-c499-4040-8a8f-e75656156e78</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
