<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Register_fas fa-user-plus fa-fw mr-1</name>
   <tag></tag>
   <elementGuidId>4217f0bd-b51a-4e3a-8f99-196b65bb760c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//aside[@id='column-right']/div/a[2]/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>i.fas.fa-user-plus.fa-fw.mr-1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>18f34629-30c7-4c77-9876-1cdac0843646</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fas fa-user-plus fa-fw mr-1</value>
      <webElementGuid>730ea484-33d5-45e6-a23d-bfa3ba0e79b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;column-right&quot;)/div[@class=&quot;list-group mb-3&quot;]/a[@class=&quot;list-group-item&quot;]/i[@class=&quot;fas fa-user-plus fa-fw mr-1&quot;]</value>
      <webElementGuid>9c7a8647-db94-4dcb-b3ee-43bcc4a46549</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//aside[@id='column-right']/div/a[2]/i</value>
      <webElementGuid>78d653d4-f6d8-4af2-b15f-16379c573ccd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[2]/i</value>
      <webElementGuid>a6fecea6-5de7-48ab-9666-bebfc83222ff</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
