<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Write Review</name>
   <tag></tag>
   <elementGuidId>cc443ff2-0190-47ac-b447-167a5335ba46</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#button-review</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='button-review']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>f3674848-3b09-420c-b3c8-c41cc7db21ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>ebdb56bb-3129-4da5-9201-6a096e91887a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>button-review</value>
      <webElementGuid>8caee15a-dd65-4b67-b330-c2388a151607</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-loading-text</name>
      <type>Main</type>
      <value>Loading...</value>
      <webElementGuid>d0342268-28f7-410c-b389-324f7d6a8188</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-lg btn-secondary</value>
      <webElementGuid>6e19d167-f92a-4d3e-a96b-5da087a56557</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Write Review</value>
      <webElementGuid>a0a332e3-9787-40a5-8ca3-77fa2a88feea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;button-review&quot;)</value>
      <webElementGuid>4cef20b1-fc13-49e2-9fd4-68dbc85fb9c5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='button-review']</value>
      <webElementGuid>82d67f2a-8942-4b6e-a087-7437fc4f122e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form-review']/div[4]/div/button</value>
      <webElementGuid>2da55d64-b8c3-4312-8b09-526240eef144</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Write a review'])[1]/following::button[1]</value>
      <webElementGuid>653829d1-fa53-4cd0-b525-87b7fc56c04e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Easy Return'])[1]/following::button[1]</value>
      <webElementGuid>27bf23b8-30d9-45cb-bda7-e6a055ae25b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='FAQ (Frequently Asked Questions)'])[1]/preceding::button[1]</value>
      <webElementGuid>c9933149-37a3-4e28-825a-0b150914ed05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='How can I change my shipping address?'])[1]/preceding::button[1]</value>
      <webElementGuid>30d858df-39ee-415d-ab41-bb7164f10140</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Write Review']/parent::*</value>
      <webElementGuid>def787dc-6e10-4455-838a-7566be42bfc4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/button</value>
      <webElementGuid>23f145bd-5148-4d3f-a0d4-3363ee61e210</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'button-review' and (text() = 'Write Review' or . = 'Write Review')]</value>
      <webElementGuid>4d593c9c-187c-49c9-a3e1-8d06160a3eb8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
