<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Write a review_text</name>
   <tag></tag>
   <elementGuidId>b2a17a86-a24c-431e-b25c-09bf7a2173a5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-review</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='input-review']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>4b34350b-7e97-4001-a497-76feebff6dcd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>3805866a-dcfc-402d-88af-495ff66b13e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>d73fbcf0-6566-490e-b582-56b3f4b34d18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-review</value>
      <webElementGuid>47d23a42-e994-4502-b8eb-2359ddc632ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Your Review</value>
      <webElementGuid>1262dc7a-8569-41b5-aac9-2f4fb69e8c71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Your Review</value>
      <webElementGuid>3bfcf4c4-e72e-4bfd-a2ab-8310d57a0a7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control form-control-lg</value>
      <webElementGuid>c688f333-ffd5-4918-b588-adf119429d34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-review&quot;)</value>
      <webElementGuid>d476a4b6-7559-4d16-9548-3cdcffd7b84a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='input-review']</value>
      <webElementGuid>fc319e75-6ba5-4e24-ad2b-3e0d124afca7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form-review']/div[3]/textarea</value>
      <webElementGuid>902f73fc-0c2d-4dad-b984-54dc6b1ca111</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/textarea</value>
      <webElementGuid>0a0820a6-80df-4318-95fb-0aa9b200e039</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'text' and @id = 'input-review' and @placeholder = 'Your Review']</value>
      <webElementGuid>446dd073-0f4a-4029-a348-9f3078103241</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
