<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Add to Cart_fas fa-heart</name>
   <tag></tag>
   <elementGuidId>9133be03-c659-498c-9d9c-ec04e58da608</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='entry_212408']/div/div/div/div/div[2]/button[2]/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.btn.btn-wishlist.wishlist-28.wished > i.fas.fa-heart</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>2054822d-e759-4738-8694-2c1032d4012c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fas fa-heart</value>
      <webElementGuid>caf18e95-ba08-4f68-a8d7-1295df7e3335</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;entry_212408&quot;)/div[@class=&quot;row&quot;]/div[@class=&quot;product-layout product-grid no-desc col-xl-4 col-lg-4 col-md-4 col-sm-6 col-6&quot;]/div[@class=&quot;product-thumb&quot;]/div[@class=&quot;product-thumb-top&quot;]/div[@class=&quot;product-action&quot;]/button[@class=&quot;btn btn-wishlist wishlist-28 wished&quot;]/i[@class=&quot;fas fa-heart&quot;]</value>
      <webElementGuid>e5d40dee-85bf-41a6-866a-371815c0118d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='entry_212408']/div/div/div/div/div[2]/button[2]/i</value>
      <webElementGuid>859607b0-8754-4b62-8c9e-1a8fa914402c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/button[2]/i</value>
      <webElementGuid>a12e7137-d691-41d1-a2e9-2aacdbd9aa4b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
