<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_to_mz_fpmax</name>
   <tag></tag>
   <elementGuidId>16ab7615-752b-4d47-88ae-5a16cc60b9c9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@name='mz_fp[max]'])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#mz-filter-panel-0-0 > div.mz-filter-group-content > div.d-flex.align-items-center > input[name=&quot;mz_fp[max]&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ae3c6bb1-182e-40a1-96fb-c05e6839768a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>0d41630f-7807-45ac-bcf5-04f4d15e10f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>mz_fp[max]</value>
      <webElementGuid>533aafa8-050c-4049-8ae2-d41e31c414e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>08bdf27f-e158-4a32-b23f-5a02a12034c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>2000</value>
      <webElementGuid>2dc6baa6-e053-4724-82e2-8714eaac70c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>101</value>
      <webElementGuid>d33f9510-7f59-46d6-b992-20e945cec478</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>max</name>
      <type>Main</type>
      <value>2000</value>
      <webElementGuid>6cf13d77-9bca-4483-8d13-0aa462a43c48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Maximum Price</value>
      <webElementGuid>58562331-147b-4d37-b34f-4d14611ac70a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Maximum Price</value>
      <webElementGuid>8dd7740c-31e0-40e9-8d22-e3400d70758e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mz-filter-panel-0-0&quot;)/div[@class=&quot;mz-filter-group-content&quot;]/div[@class=&quot;d-flex align-items-center&quot;]/input[@class=&quot;form-control&quot;]</value>
      <webElementGuid>72a6e997-e955-48dd-b2e4-bcd2aefe8a4a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@name='mz_fp[max]'])[2]</value>
      <webElementGuid>2da6940f-5934-4eb0-a4d9-287f3dc048ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mz-filter-panel-0-0']/div/div[2]/input[2]</value>
      <webElementGuid>ed94ea79-4f95-47ec-89a0-7916fe2a7a41</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div/div[2]/input[2]</value>
      <webElementGuid>9dd59392-ca42-4435-9637-4222d48a2e67</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @name = 'mz_fp[max]' and @placeholder = 'Maximum Price']</value>
      <webElementGuid>8c58c652-1fc8-4e5a-8a28-0778b75130c4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
