<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_85.00_btn btn-info</name>
   <tag></tag>
   <elementGuidId>0d33d2f6-4163-4d22-89a6-3a42ef77f914</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.btn.btn-info</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='content']/div/table/tbody/tr/td[7]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>9cccb85b-4d77-4917-b812-2da3e4ca0814</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://ecommerce-playground.lambdatest.io/index.php?route=account/order/info&amp;order_id=4708</value>
      <webElementGuid>d64a1505-dbb5-4857-a4db-287a36f5818e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>tooltip</value>
      <webElementGuid>ec9bc080-cec4-4502-be7d-1becc7e24801</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-info</value>
      <webElementGuid>d0fdcb50-3814-42b3-8d09-c76bfece00e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-original-title</name>
      <type>Main</type>
      <value>View</value>
      <webElementGuid>db7c46fc-d28d-4a6c-a630-62650383ce8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>tooltip359408</value>
      <webElementGuid>a584a651-fb28-402b-9b2c-bc41cc049454</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;content&quot;)/div[@class=&quot;table-responsive&quot;]/table[@class=&quot;table table-bordered table-hover&quot;]/tbody[1]/tr[1]/td[@class=&quot;text-right&quot;]/a[@class=&quot;btn btn-info&quot;]</value>
      <webElementGuid>b1ba8742-95aa-4878-951d-fa5fa3a3e023</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/div/table/tbody/tr/td[7]/a</value>
      <webElementGuid>6f1329fe-6b1c-4f73-9a2b-9faff5e12dbb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$85.00'])[1]/following::a[1]</value>
      <webElementGuid>33723a62-a09f-482a-a38b-62f470cb1caa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pending'])[1]/following::a[1]</value>
      <webElementGuid>2e736886-be0b-4bb0-a08b-ace30e2bbb5f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='#4707'])[1]/preceding::a[1]</value>
      <webElementGuid>c32fe9f7-cdd6-47b0-a72f-a1a9b61ba4b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tripti 123 Pandey'])[2]/preceding::a[1]</value>
      <webElementGuid>83fa8b5a-ff5a-40af-b45d-c863aca1c3d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://ecommerce-playground.lambdatest.io/index.php?route=account/order/info&amp;order_id=4708')]</value>
      <webElementGuid>13c7a076-c0a9-47c9-9ca9-ae7a499aa8fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[7]/a</value>
      <webElementGuid>b7b16867-3f70-4a01-bfee-2ac618a1f6e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://ecommerce-playground.lambdatest.io/index.php?route=account/order/info&amp;order_id=4708']</value>
      <webElementGuid>8e3da00d-c8e4-4ffb-8fa9-c2a44cb019b6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
