<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Delete</name>
   <tag></tag>
   <elementGuidId>4b2f994d-3b97-4a1c-8a0d-da35c6fbb52d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='content']/div/table/tbody/tr[2]/td[2]/a[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>tr:nth-of-type(2) > td.text-right.p-3 > a.btn.btn-danger</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>e5f240bc-062d-410a-a2de-ac0300cb2573</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://ecommerce-playground.lambdatest.io/index.php?route=account/address/delete&amp;address_id=3327</value>
      <webElementGuid>af307d8c-a80d-47b7-99d2-ea2ffc3e9976</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-danger</value>
      <webElementGuid>3fab4a78-5e35-4161-90e0-4bec00446c76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Delete</value>
      <webElementGuid>1792ad12-6679-4ba9-a825-48035a4107c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;content&quot;)/div[@class=&quot;table-responsive&quot;]/table[@class=&quot;table table-bordered table-hover&quot;]/tbody[1]/tr[2]/td[@class=&quot;text-right p-3&quot;]/a[@class=&quot;btn btn-danger&quot;]</value>
      <webElementGuid>c05bdbf3-1672-4823-b2cb-6f94b678c0b5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/div/table/tbody/tr[2]/td[2]/a[2]</value>
      <webElementGuid>d0905eb2-6c5b-40a5-9013-f8560fdd7b9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Delete')])[2]</value>
      <webElementGuid>2db22e07-3358-44ab-bb72-b27d3826f839</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Edit'])[2]/following::a[1]</value>
      <webElementGuid>ee0f9ebd-e0fd-4421-a191-017c68ec73a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='triptipandy AnkitcomapnyAddress oneAddress twonoida 201307Uttar PradeshIndia'])[1]/following::a[2]</value>
      <webElementGuid>eabafc24-5960-41f6-9466-3d36ef72cf3f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='triptipandy AnkitcomapnyAddress oneAddress twonoida 201307Uttar PradeshIndia'])[2]/preceding::a[1]</value>
      <webElementGuid>5870b001-1ec2-444c-b005-5c2ff5d782d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Edit'])[3]/preceding::a[1]</value>
      <webElementGuid>ccdd47f8-5909-461d-8e86-1ea1358ab021</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://ecommerce-playground.lambdatest.io/index.php?route=account/address/delete&amp;address_id=3327')]</value>
      <webElementGuid>d87edb95-b316-4b0f-813c-4b4556892516</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[2]/a[2]</value>
      <webElementGuid>f25639df-b0d1-4b88-baa8-174be0ef648e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://ecommerce-playground.lambdatest.io/index.php?route=account/address/delete&amp;address_id=3327' and (text() = 'Delete' or . = 'Delete')]</value>
      <webElementGuid>96723248-7c10-456d-a2b9-711647466b66</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
