<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Your address has been successfully update_81df92</name>
   <tag></tag>
   <elementGuidId>b3a56941-7e9b-48ef-aea5-9140428c8d40</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='account-address']/div/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>i.fa.fa-check-circle</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>fdda77ae-60ef-4e26-a640-0b52418a268a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-check-circle</value>
      <webElementGuid>0efcdfe9-7f56-4607-9b77-6eea7af76190</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;account-address&quot;)/div[@class=&quot;alert alert-success alert-dismissible&quot;]/i[@class=&quot;fa fa-check-circle&quot;]</value>
      <webElementGuid>46f7eafd-1d8e-436b-9cec-3f0ef0945b84</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='account-address']/div/i</value>
      <webElementGuid>583db2fe-ab10-4690-aa94-a654528e5338</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/i</value>
      <webElementGuid>8fb4d4ef-05aa-4397-859d-b9eb1186752a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
