<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Address 2_address_2</name>
   <tag></tag>
   <elementGuidId>cdd41efc-af42-4e48-b0bd-317eed00c779</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-address-2']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#input-address-2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>fb7e9ab7-0e61-415c-a86b-0de383884d99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>84804102-3807-481d-8ff2-fe076c62a162</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>address_2</value>
      <webElementGuid>8e37d7c3-3dce-4c92-b1e1-4f107f2e2fdc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Address 2</value>
      <webElementGuid>3f71395e-5735-4e43-9d1c-6bcc778fa9e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-address-2</value>
      <webElementGuid>89944a18-4938-4bf6-83b4-8f2aac7c36f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>eb392503-b53b-4519-aa7a-8965e4528e67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-address-2&quot;)</value>
      <webElementGuid>8955d8d4-e12f-498a-80dd-2f42ba1bd118</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-address-2']</value>
      <webElementGuid>0b90af5a-979f-41a1-8bfb-ae344638eeb7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/form/fieldset/div[5]/div/input</value>
      <webElementGuid>042de516-a837-4240-b8cf-a7b6797b42b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/input</value>
      <webElementGuid>87403abe-1877-43ee-956e-a4cb1de5ef94</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'address_2' and @placeholder = 'Address 2' and @id = 'input-address-2']</value>
      <webElementGuid>cf8d6152-7c12-4bb0-b1c0-93e4706d0c0e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
