<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_--- Please Select --- Andaman and Ni_f71a83</name>
   <tag></tag>
   <elementGuidId>4e9e8c65-0b73-4794-b618-df3a192737a2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='input-zone']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#input-zone</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>a70bf6d3-6582-4f0d-a1a0-0c52fb6ade4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>zone_id</value>
      <webElementGuid>c35af40d-f565-40dc-9da3-4f09e5bb8de8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-zone</value>
      <webElementGuid>05a9f665-8dcb-4c42-b8cf-3a44b508b7ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>custom-select</value>
      <webElementGuid>35ed6411-e9ee-4456-90ca-21ac94230a9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> --- Please Select --- Andaman and Nicobar IslandsAndhra PradeshArunachal PradeshAssamBiharChandigarhDadra and Nagar HaveliDaman and DiuDelhiGoaGujaratHaryanaHimachal PradeshJammu and KashmirKarnatakaKeralaLakshadweep IslandsMadhya PradeshMaharashtraManipurMeghalayaMizoramNagalandOrissaPuducherryPunjabRajasthanSikkimTamil NaduTelanganaTripuraUttar PradeshWest Bengal</value>
      <webElementGuid>fad943a6-d840-4042-b32f-e680747bac1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-zone&quot;)</value>
      <webElementGuid>37ce1c52-ff3a-4df5-8dd3-3f57f21d6221</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='input-zone']</value>
      <webElementGuid>9d35b808-5d77-4f1b-8a32-718e0ab24936</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/form/fieldset/div[9]/div/select</value>
      <webElementGuid>4387becc-ab34-4b12-901c-12f21ea9ca1a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Region / State'])[1]/following::select[1]</value>
      <webElementGuid>6acc9f26-1655-4cae-926d-f5baaf86b6fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Country'])[1]/following::select[2]</value>
      <webElementGuid>030dd4ae-620b-49f7-8849-87e7b2092d0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Default Address'])[1]/preceding::select[1]</value>
      <webElementGuid>39d376ae-892b-483f-9587-27e279686b87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Yes'])[1]/preceding::select[1]</value>
      <webElementGuid>57ce0529-7b39-4282-8a4d-7562f43af690</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div/select</value>
      <webElementGuid>c35aeac6-006e-4b9d-9cc1-89e1a928bd0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'zone_id' and @id = 'input-zone' and (text() = ' --- Please Select --- Andaman and Nicobar IslandsAndhra PradeshArunachal PradeshAssamBiharChandigarhDadra and Nagar HaveliDaman and DiuDelhiGoaGujaratHaryanaHimachal PradeshJammu and KashmirKarnatakaKeralaLakshadweep IslandsMadhya PradeshMaharashtraManipurMeghalayaMizoramNagalandOrissaPuducherryPunjabRajasthanSikkimTamil NaduTelanganaTripuraUttar PradeshWest Bengal' or . = ' --- Please Select --- Andaman and Nicobar IslandsAndhra PradeshArunachal PradeshAssamBiharChandigarhDadra and Nagar HaveliDaman and DiuDelhiGoaGujaratHaryanaHimachal PradeshJammu and KashmirKarnatakaKeralaLakshadweep IslandsMadhya PradeshMaharashtraManipurMeghalayaMizoramNagalandOrissaPuducherryPunjabRajasthanSikkimTamil NaduTelanganaTripuraUttar PradeshWest Bengal')]</value>
      <webElementGuid>544ffcfb-19c0-4839-8e4a-9e065b5c5af3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
