<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Login__18u87m _3WuvDp</name>
   <tag></tag>
   <elementGuidId>8e08c1eb-dddc-4694-81d5-ea5021a255fe</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input._18u87m._3WuvDp</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@value=''])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>07bf48c3-ad2c-4d6e-bc75-7951ea678aa9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>40a8e16c-acf7-48f6-904d-0638feb93a88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>358dbd0b-03e2-46b1-b2e1-3897a989d542</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_18u87m _3WuvDp</value>
      <webElementGuid>e87ec203-7cde-4dbe-83c3-1e3afdc44b70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-focusvisible-polyfill</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>2361cfe6-4058-47ea-877c-493f5e634e3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;useInterFont en-fonts-loaded&quot;]/body[@class=&quot;fk-modal-visible&quot;]/div[@class=&quot;fbDBuK _3CYmv5&quot;]/div[@class=&quot;JFPqaw&quot;]/div[@class=&quot;_17UxrZ&quot;]/div[@class=&quot;_1E5Hij&quot;]/div[@class=&quot;_3skCyB&quot;]/div[1]/form[1]/div[@class=&quot;_22Dgdy _29BEA8&quot;]/input[@class=&quot;_18u87m _3WuvDp&quot;]</value>
      <webElementGuid>ffc38f1a-9d0a-4807-91df-e1f904b2f5f5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@value=''])[2]</value>
      <webElementGuid>14df3760-2004-4e22-9eab-37656d45e333</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/form/div/input</value>
      <webElementGuid>2a5077e6-586d-4b08-8094-45db373d7d03</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text']</value>
      <webElementGuid>5aa663b7-aac1-49f6-96f2-eccee376473d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
