<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_--- Please Select --- Andaman and Ni_f71a83</name>
   <tag></tag>
   <elementGuidId>9b2a31b8-71bf-4062-9b68-61b11780582d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='input-payment-zone']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#input-payment-zone</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>47aa9c1d-eabc-4543-8def-0de3da6d400b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>zone_id</value>
      <webElementGuid>ea01bcee-76cd-4868-a017-ec2cd2c8545f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-payment-zone</value>
      <webElementGuid>6a20eadb-63f2-45f2-bc71-d8d1c19d0d07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>custom-select</value>
      <webElementGuid>30ceecd0-746e-48f2-bb85-efc2253328d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> --- Please Select --- Andaman and Nicobar IslandsAndhra PradeshArunachal PradeshAssamBiharChandigarhDadra and Nagar HaveliDaman and DiuDelhiGoaGujaratHaryanaHimachal PradeshJammu and KashmirKarnatakaKeralaLakshadweep IslandsMadhya PradeshMaharashtraManipurMeghalayaMizoramNagalandOrissaPuducherryPunjabRajasthanSikkimTamil NaduTelanganaTripuraUttar PradeshWest Bengal</value>
      <webElementGuid>563f5a5a-6a19-4eb5-b94f-f62177c175cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-payment-zone&quot;)</value>
      <webElementGuid>5f39770c-cdc6-43cf-9c78-db778581ef32</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='input-payment-zone']</value>
      <webElementGuid>740b635c-f0d3-4f75-944e-ca19feec30b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='payment-new']/div[9]/div/select</value>
      <webElementGuid>bb8ad8ff-ab61-4ba8-8260-b7ea43fcd94d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Region / State'])[1]/following::select[1]</value>
      <webElementGuid>936d7c17-a557-4ad1-a0d2-672291f632fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Country'])[1]/following::select[2]</value>
      <webElementGuid>2b40fac2-0b87-4373-9182-97e27afb95d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='My delivery and billing addresses are the same.'])[1]/preceding::select[1]</value>
      <webElementGuid>9dddc107-d85e-4f87-9dc2-c76da23456d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Shipping Address'])[1]/preceding::select[1]</value>
      <webElementGuid>36f60b04-e441-492a-9099-a7e3744fb675</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div/select</value>
      <webElementGuid>5e73fbe9-ad9a-486d-9359-e8b3c6f2ce99</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'zone_id' and @id = 'input-payment-zone' and (text() = ' --- Please Select --- Andaman and Nicobar IslandsAndhra PradeshArunachal PradeshAssamBiharChandigarhDadra and Nagar HaveliDaman and DiuDelhiGoaGujaratHaryanaHimachal PradeshJammu and KashmirKarnatakaKeralaLakshadweep IslandsMadhya PradeshMaharashtraManipurMeghalayaMizoramNagalandOrissaPuducherryPunjabRajasthanSikkimTamil NaduTelanganaTripuraUttar PradeshWest Bengal' or . = ' --- Please Select --- Andaman and Nicobar IslandsAndhra PradeshArunachal PradeshAssamBiharChandigarhDadra and Nagar HaveliDaman and DiuDelhiGoaGujaratHaryanaHimachal PradeshJammu and KashmirKarnatakaKeralaLakshadweep IslandsMadhya PradeshMaharashtraManipurMeghalayaMizoramNagalandOrissaPuducherryPunjabRajasthanSikkimTamil NaduTelanganaTripuraUttar PradeshWest Bengal')]</value>
      <webElementGuid>e25e6e76-14b2-4777-8e26-0d1b5bfe7512</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
