<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_4</name>
   <tag></tag>
   <elementGuidId>6b2a618b-e5e3-4208-8383-65eac0a9d6dc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='form-review']/div/span/label[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>label:nth-of-type(2)</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>42702a16-e53c-48c6-a15a-36ef581c0d00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>rating-4-216860</value>
      <webElementGuid>7a8542f6-9489-40f0-af7a-da3e755dfb95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>fd563e04-69fb-49c5-b38e-dc9a98acf578</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;form-review&quot;)/div[@class=&quot;form-group select-rating d-flex flex-wrap&quot;]/span[@class=&quot;start-form-check&quot;]/label[2]</value>
      <webElementGuid>308282d7-0444-4aa9-b90f-8d8c0a96de3b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form-review']/div/span/label[2]</value>
      <webElementGuid>9f82c4d4-9e59-4a18-97c1-69dad209f245</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Easy Return'])[1]/following::label[2]</value>
      <webElementGuid>0e264480-ce57-4b9d-a557-05bdfff1589d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Online payment'])[1]/following::label[2]</value>
      <webElementGuid>ae01d956-3dcc-468e-bf40-a9fa07710f69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Write a review'])[1]/preceding::label[5]</value>
      <webElementGuid>ae39db90-330b-4b59-8f6e-79720e634167</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Warning: Please select a review rating!'])[1]/preceding::label[5]</value>
      <webElementGuid>c801932b-3563-45ad-a182-7caddc669640</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='4']/parent::*</value>
      <webElementGuid>fb0724b0-4c6b-4018-9bff-2a9772a94671</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label[2]</value>
      <webElementGuid>99719c8b-dfaf-4595-b070-78e8e71fe952</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = '4' or . = '4')]</value>
      <webElementGuid>d84ced42-cb03-4db4-99b5-6cbc5b5c9046</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
