<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Write a review_text</name>
   <tag></tag>
   <elementGuidId>74b276d2-7ae7-4028-8cb2-cf11945e7f5c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-review</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='input-review']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>5aa3e91d-fa1e-440b-a2aa-537164e1f038</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>dfd532ae-e197-4a08-9aec-1710192d825a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>c22af082-a9dc-4b8e-83b2-e4fc94c89577</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-review</value>
      <webElementGuid>94e1da22-ccd6-4bbe-8981-ab97bb792544</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Your Review</value>
      <webElementGuid>2e5410fc-dea7-4ae6-8e29-e6d2ecbbdd46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Your Review</value>
      <webElementGuid>23da4ec4-278c-4af6-8635-0207d3201c04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control form-control-lg</value>
      <webElementGuid>12f466d7-0bba-47b5-a7d5-fad16fa4f95a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-review&quot;)</value>
      <webElementGuid>4ba1bd41-01ba-466f-981e-2ebf30cfbcf2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='input-review']</value>
      <webElementGuid>e2ce912d-d56b-427d-a3f1-abfee1854f51</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form-review']/div[3]/textarea</value>
      <webElementGuid>fa1d4ed0-4922-49d0-8190-dc938a49102c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/textarea</value>
      <webElementGuid>6318625a-faa8-4446-b435-d0b39c179d6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'text' and @id = 'input-review' and @placeholder = 'Your Review']</value>
      <webElementGuid>38d7aec9-9090-4c37-ade8-af9f34f8f1a4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
