<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Headphones</name>
   <tag></tag>
   <elementGuidId>22f42328-d080-41b2-bdd9-1d52e2aaeae5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='entry281_216480']/div/div/ul/li/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#entry281_216480 > div.menu-wraper.image-bottom.vertical > div.menu-items.d-flex.align-items-start > ul.nav.flex-column.vertical > li.nav-item > a.nav-link.icon-left.text</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>fef8233f-5c66-4861-8e35-ac5a320bc6b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-link icon-left text</value>
      <webElementGuid>24315306-f872-4369-b0ca-45b0c6638ce2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://ecommerce-playground.lambdatest.io/index.php?route=product/category&amp;path=25</value>
      <webElementGuid>c93a6466-6089-4fb9-82af-f79e61e181d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Headphones</value>
      <webElementGuid>379c2168-256f-4ae8-82dd-0c95d49eaf36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
Headphones
</value>
      <webElementGuid>23ec061d-a88d-4207-a31d-d2bb70111cc3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;entry281_216480&quot;)/div[@class=&quot;menu-wraper image-bottom vertical&quot;]/div[@class=&quot;menu-items d-flex align-items-start&quot;]/ul[@class=&quot;nav flex-column vertical&quot;]/li[@class=&quot;nav-item&quot;]/a[@class=&quot;nav-link icon-left text&quot;]</value>
      <webElementGuid>04b421fa-ca2a-43bc-a33a-be293bcb8a32</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='entry281_216480']/div/div/ul/li/a</value>
      <webElementGuid>658edc7c-f57e-412b-a050-75104509245d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Headphones')]</value>
      <webElementGuid>5b76e979-a71e-4175-ab62-eab3859518f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Accessories'])[1]/following::a[1]</value>
      <webElementGuid>745e1eb0-45ed-4798-b134-79a212b678db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lenovo'])[1]/following::a[1]</value>
      <webElementGuid>84ec3d67-8179-4996-aed4-c8d182b48ef0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Memory Card'])[1]/preceding::a[1]</value>
      <webElementGuid>202beb44-a8d2-483d-8a75-26078d3f0a07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mobile cases'])[1]/preceding::a[2]</value>
      <webElementGuid>86669c03-163c-401f-ba98-6d161e44ed96</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Headphones']/parent::*</value>
      <webElementGuid>9cdbe540-3d33-408d-ae29-35eac0c4c70e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'https://ecommerce-playground.lambdatest.io/index.php?route=product/category&amp;path=25')])[2]</value>
      <webElementGuid>4dcbee6f-8e34-4c71-9936-9cd7c5a39f7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/ul/li/a</value>
      <webElementGuid>73946ef3-9691-42c5-9ac3-59c22468cafa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://ecommerce-playground.lambdatest.io/index.php?route=product/category&amp;path=25' and @title = 'Headphones' and (text() = '
Headphones
' or . = '
Headphones
')]</value>
      <webElementGuid>541f4185-ef5c-47a7-9e9c-f334ead6f90d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
